version: "3"
agent:
  web_addr: 127.0.0.1:4041
  authtoken: 3CwxAUuhdXTMtczD0ld1nd1pGUy_5w9yz4UtJvoj2EJnUNNRJ
tunnels:
  clientes:
    proto: http
    addr: 8010
  productos:
    proto: http
    addr: 8001
  pedidos:
    proto: http
    addr: 8002
  inventario:
    proto: http
    addr: 8003
