services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: shopnow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16
    container_name: shopnow-postgres
    environment:
      POSTGRES_DB: shopnow_663n
      POSTGRES_USER: shopnow_663n_user
      POSTGRES_PASSWORD: shopnow_local_123
    ports:
      - "5432:5432"
    volumes:
      - shopnow_pgdata:/var/lib/postgresql/data

  clientes:
    build:
      context: .
      dockerfile: Dockerfile.clientes
    environment:
      SHOPNOW_STORAGE: postgres
      DATABASE_URL: postgresql://shopnow_663n_user:shopnow_local_123@postgres:5432/shopnow_663n
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8010:8010"

  productos:
    build:
      context: .
      dockerfile: Dockerfile.productos
    environment:
      SHOPNOW_STORAGE: postgres
      DATABASE_URL: postgresql://shopnow_663n_user:shopnow_local_123@postgres:5432/shopnow_663n
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8001:8001"

  inventario:
    build:
      context: .
      dockerfile: Dockerfile.inventario
    environment:
      SHOPNOW_STORAGE: postgres
      DATABASE_URL: postgresql://shopnow_663n_user:shopnow_local_123@postgres:5432/shopnow_663n
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8003:8003"

  pedidos:
    build:
      context: .
      dockerfile: Dockerfile.pedidos
    environment:
      SHOPNOW_STORAGE: postgres
      DATABASE_URL: postgresql://shopnow_663n_user:shopnow_local_123@postgres:5432/shopnow_663n
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      CLIENTES_URL: http://clientes:8010
      PRODUCTOS_URL: http://productos:8001
      INVENTARIO_URL: http://inventario:8003
      SERVICE_AUTH_USER: admin
      SERVICE_AUTH_PASSWORD: admin123
    depends_on:
      - postgres
      - rabbitmq
      - clientes
      - productos
      - inventario
    ports:
      - "8002:8002"

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    environment:
      CLIENTES_URL: http://clientes:8010
      PRODUCTOS_URL: http://productos:8001
      PEDIDOS_URL: http://pedidos:8002
      INVENTARIO_URL: http://inventario:8003
    depends_on:
      - clientes
      - productos
      - pedidos
      - inventario
    ports:
      - "8090:8090"

volumes:
  shopnow_pgdata:
