services:

  - type: web
    name: shopnow-clientes
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn serv_clientes:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SHOPNOW_STORAGE
        value: postgres
      - key: SHOPNOW_SEED_DEMO
        value: "true"
      - key: POSTGRES_HOST
        value: dpg-d7ohmhpj2pic73abp6l0-a.oregon-postgres.render.com
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        value: shopnow_663n
      - key: POSTGRES_USER
        value: shopnow_663n_user
      - key: POSTGRES_PASSWORD
        value: mJKZ4Bs3pW5XqeK5c5FLIukVy1TUGEII
      - key: POSTGRES_SSLMODE
        value: require
      - key: RABBITMQ_HOST
        value: beaver.rmq.cloudamqp.com
      - key: RABBITMQ_PORT
        value: "5672"
      - key: RABBITMQ_USER
        value: dbyjxysd
      - key: RABBITMQ_PASSWORD
        value: ArQa8_E5tvktqoEjYLidEorEDPwEjBfT
      - key: RABBITMQ_VHOST
        value: dbyjxysd

  - type: web
    name: shopnow-productos
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn serv_productos:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SHOPNOW_STORAGE
        value: postgres
      - key: SHOPNOW_SEED_DEMO
        value: "true"
      - key: POSTGRES_HOST
        value: dpg-d7ohmhpj2pic73abp6l0-a.oregon-postgres.render.com
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        value: shopnow_663n
      - key: POSTGRES_USER
        value: shopnow_663n_user
      - key: POSTGRES_PASSWORD
        value: mJKZ4Bs3pW5XqeK5c5FLIukVy1TUGEII
      - key: POSTGRES_SSLMODE
        value: require
      - key: RABBITMQ_HOST
        value: beaver.rmq.cloudamqp.com
      - key: RABBITMQ_PORT
        value: "5672"
      - key: RABBITMQ_USER
        value: dbyjxysd
      - key: RABBITMQ_PASSWORD
        value: ArQa8_E5tvktqoEjYLidEorEDPwEjBfT
      - key: RABBITMQ_VHOST
        value: dbyjxysd

  - type: web
    name: shopnow-pedidos
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn serv_pedidos:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SHOPNOW_STORAGE
        value: postgres
      - key: SHOPNOW_SEED_DEMO
        value: "true"
      - key: POSTGRES_HOST
        value: dpg-d7ohmhpj2pic73abp6l0-a.oregon-postgres.render.com
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        value: shopnow_663n
      - key: POSTGRES_USER
        value: shopnow_663n_user
      - key: POSTGRES_PASSWORD
        value: mJKZ4Bs3pW5XqeK5c5FLIukVy1TUGEII
      - key: POSTGRES_SSLMODE
        value: require
      - key: RABBITMQ_HOST
        value: beaver.rmq.cloudamqp.com
      - key: RABBITMQ_PORT
        value: "5672"
      - key: RABBITMQ_USER
        value: dbyjxysd
      - key: RABBITMQ_PASSWORD
        value: ArQa8_E5tvktqoEjYLidEorEDPwEjBfT
      - key: RABBITMQ_VHOST
        value: dbyjxysd
      - key: CLIENTES_URL
        value: https://shopnow-clientes-nlyo.onrender.com
      - key: PRODUCTOS_URL
        value: https://shopnow-productos-b175.onrender.com
      - key: INVENTARIO_URL
        value: https://shopnow-inventario-u5ua.onrender.com
      - key: SERVICE_AUTH_USER
        value: admin
      - key: SERVICE_AUTH_PASSWORD
        value: admin123

  - type: web
    name: shopnow-inventario
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn serv_inventario:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SHOPNOW_STORAGE
        value: postgres
      - key: SHOPNOW_SEED_DEMO
        value: "true"
      - key: POSTGRES_HOST
        value: dpg-d7ohmhpj2pic73abp6l0-a.oregon-postgres.render.com
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        value: shopnow_663n
      - key: POSTGRES_USER
        value: shopnow_663n_user
      - key: POSTGRES_PASSWORD
        value: mJKZ4Bs3pW5XqeK5c5FLIukVy1TUGEII
      - key: POSTGRES_SSLMODE
        value: require
      - key: RABBITMQ_HOST
        value: beaver.rmq.cloudamqp.com
      - key: RABBITMQ_PORT
        value: "5672"
      - key: RABBITMQ_USER
        value: dbyjxysd
      - key: RABBITMQ_PASSWORD
        value: ArQa8_E5tvktqoEjYLidEorEDPwEjBfT
      - key: RABBITMQ_VHOST
        value: dbyjxysd

  - type: web
    name: shopnow-gateway
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn gateway:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CLIENTES_URL
        value: https://shopnow-clientes-nlyo.onrender.com
      - key: PRODUCTOS_URL
        value: https://shopnow-productos-b175.onrender.com
      - key: PEDIDOS_URL
        value: https://shopnow-pedidos-dnq3.onrender.com
      - key: INVENTARIO_URL
        value: https://shopnow-inventario-u5ua.onrender.com
