BEGIN;

CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    correo VARCHAR(255) NOT NULL UNIQUE,
    direccion VARCHAR(255) NOT NULL,
    telefono VARCHAR(10) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    rfc VARCHAR(20) NOT NULL DEFAULT '',
    fecha_registro DATE
);

CREATE TABLE IF NOT EXISTS productos (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(150) NOT NULL,
    precio NUMERIC(10,2) NOT NULL CHECK (precio > 0),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    categoria VARCHAR(100) NOT NULL DEFAULT 'General'
);

CREATE TABLE IF NOT EXISTS inventario (
    id_producto INTEGER PRIMARY KEY REFERENCES productos(id_producto) ON DELETE CASCADE,
    cantidad INTEGER NOT NULL CHECK (cantidad >= 0)
);

CREATE TABLE IF NOT EXISTS pedidos (
    id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL REFERENCES clientes(id_cliente),
    id_producto INTEGER NOT NULL REFERENCES productos(id_producto),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0)
);

CREATE INDEX IF NOT EXISTS idx_pedidos_cliente ON pedidos (id_cliente);
CREATE INDEX IF NOT EXISTS idx_pedidos_producto ON pedidos (id_producto);

CREATE OR REPLACE FUNCTION sp_validar_stock(
    p_id_producto INTEGER,
    p_cantidad INTEGER
)
RETURNS TABLE(existe_producto BOOLEAN, stock_actual INTEGER, stock_suficiente BOOLEAN)
LANGUAGE plpgsql
AS $$
DECLARE
    v_stock INTEGER;
BEGIN
    SELECT i.cantidad
    INTO v_stock
    FROM inventario i
    WHERE i.id_producto = p_id_producto;

    IF v_stock IS NULL THEN
        RETURN QUERY SELECT FALSE, 0, FALSE;
        RETURN;
    END IF;

    RETURN QUERY
    SELECT TRUE, v_stock, (v_stock >= p_cantidad);
END;
$$;

CREATE OR REPLACE FUNCTION sp_descontar_inventario(
    p_id_producto INTEGER,
    p_cantidad INTEGER
)
RETURNS TABLE(exito BOOLEAN, nueva_cantidad INTEGER, error TEXT)
LANGUAGE plpgsql
AS $$
DECLARE
    v_stock INTEGER;
BEGIN
    SELECT i.cantidad
    INTO v_stock
    FROM inventario i
    WHERE i.id_producto = p_id_producto
    FOR UPDATE;

    IF v_stock IS NULL THEN
        RETURN QUERY SELECT FALSE, NULL::INTEGER, 'Producto no encontrado';
        RETURN;
    END IF;

    IF v_stock < p_cantidad THEN
        RETURN QUERY SELECT FALSE, v_stock, 'Stock insuficiente';
        RETURN;
    END IF;

    UPDATE inventario
    SET cantidad = cantidad - p_cantidad
    WHERE id_producto = p_id_producto
    RETURNING cantidad INTO v_stock;

    RETURN QUERY SELECT TRUE, v_stock, NULL::TEXT;
END;
$$;

CREATE OR REPLACE FUNCTION sp_crear_pedido(
    p_id_cliente INTEGER,
    p_id_producto INTEGER,
    p_cantidad INTEGER
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_pedido INTEGER;
BEGIN
    INSERT INTO pedidos (id_cliente, id_producto, cantidad)
    VALUES (p_id_cliente, p_id_producto, p_cantidad)
    RETURNING id_pedido INTO v_id_pedido;

    RETURN v_id_pedido;
END;
$$;

COMMIT;
